### ISSUE TITLE
Error message shown!

### ISSUE THREAD

**Issue by DonZheng** [MrShadowDev/Free-Canva-Pro-Lifetime#4]
![image](https://github.com/MrShadowDev/Free-Canva-Pro-Lifetime/assets/40833875/c099b776-eb72-4987-a4d1-abd4ed946118)

I'm experiencing this error. Can you please help?

**Comment by MrShadowDev** [comment]
Yes i need to update the link because its not working anymore.

**Comment by DonZheng** [comment]
Thanks Buddy. Wondering if you have any timeline in mind?

**Comment by MrShadowDev** [comment]
Maybe this weekend
