### ISSUE TITLE
please help!!!

### ISSUE THREAD

**Issue by hmm-star** [MrShadowDev/Free-Canva-Pro-Lifetime#9]
i did everything , followed every instruction and even after waiting 5 minutes no file was created with the link.
Dear sir, please help me, after giving the command i see the following
```
C:\Users\x\Downloads\Free-Canva-Pro-Lifetime-main>python run.py

C:\Users\x\Downloads\Free-Canva-Pro-Lifetime-main>
```

**Comment by MrShadowDev** [comment]
You installed dependencies?  Execute the .bat file

**Comment by MrShadowDev** [comment]
Find the issue fixing it rn!

**Comment by MrShadowDev** [comment]
Working!
